LeitorNfe2/Controllers/AddressesController.cs
using LeitorNfe2.Data;
using LeitorNfe2.Models.Domain;
using LeitorNfe2.Models;
using Microsoft.AspNetCore.Mvc;

namespace LeitorNfe2.Controllers
{
    public class AddressesController : Controller
    {
        private readonly LeitorContext leitorContext;
        public AddressesController(LeitorContext leitorContext)
        {
            this.leitorContext = leitorContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddAddressViewModel request)
        {
            var address = new Address()
            {
                Id = Guid.NewGuid(),
                PublicPlace = request.PublicPlace,
                Number = request.Number,
                District = request.District,
                County = request.County,
                State = request.State,
                ZipCode = request.ZipCode,
            };

            await leitorContext.Addresses.AddAsync(address);
            await leitorContext.SaveChangesAsync();

            return RedirectToAction("Add");
        }
    }
}

LeitorNfe2/Controllers/InvoicesController.cs
using LeitorNfe2.Data;
using LeitorNfe2.Models;
using LeitorNfe2.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Xml;

namespace LeitorNfe2.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly LeitorContext leitorContext;
        public InvoicesController(LeitorContext leitorContext)
        {
            this.leitorContext = leitorContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var invoices = await leitorContext.Invoices.ToListAsync();
            return View(invoices);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddInvoiceViewModel invoiceViewModel)
        {
            var invoice = new Invoice()
            {
                Id = Guid.NewGuid(),
                Number = invoiceViewModel.Number,
                AccessKey = invoiceViewModel.AccessKey,
                IssueDate = invoiceViewModel.IssueDate,
                IssuerId = invoiceViewModel.IssuerId,
                AddresseeId = invoiceViewModel.AddresseeId,
                ProductId = invoiceViewModel.ProductId,
                TotalValue = invoiceViewModel.TotalValue,
                Description = invoiceViewModel.Description,
                OrderNumber = invoiceViewModel.OrderNumber
            };

            await leitorContext.Invoices.AddAsync(invoice);
            await leitorContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id) 
        {
            var invoice = await leitorContext.Invoices.FirstOrDefaultAsync(x => x.Id == id);

            if (invoice != null)
            {
                var viewModel = new UpdateInvoiceViewModel()
                {
                    Id = invoice.Id,
                    Number = invoice.Number,
                    AccessKey = invoice.AccessKey,
                    IssueDate = invoice.IssueDate,
                    IssuerId = invoice.IssuerId,
                    AddresseeId = invoice.AddresseeId,
                    ProductId = invoice.ProductId,
                    TotalValue = invoice.TotalValue,
                    Description = invoice.Description,
                    OrderNumber = invoice.OrderNumber
                };

                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateInvoiceViewModel model) 
        {
            var invoice = await leitorContext.Invoices.FindAsync(model.Id);

            if (invoice != null) 
            {
                invoice.Description = model.Description;
                invoice.OrderNumber = model.OrderNumber;
                await leitorContext.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateInvoiceViewModel model) 
        { 
            var invoice = await leitorContext.Invoices.FindAsync(model.Id);

            if(invoice != null) 
            { 
                leitorContext.Invoices.Remove(invoice);
                await leitorContext.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
    }
}

LeitorNfe2/Controllers/IssuersController.cs
using LeitorNfe2.Data;
using LeitorNfe2.Models;
using LeitorNfe2.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Xml;

namespace LeitorNfe2.Controllers
{
    public class IssuersController : Controller
    {
        private readonly LeitorContext leitorContext;
        public IssuersController(LeitorContext leitorContext)
        {
            this.leitorContext = leitorContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddIssuerViewModel request)
        {
            var issuer = new Issuer()
            {
                Id = Guid.NewGuid(),
                Name = request.Name,
                Cnpj = request.Cnpj,
                AddressId = request.AddressId,
                Email = request.Email
            };

            await leitorContext.Issuers.AddAsync(issuer);
            await leitorContext.SaveChangesAsync();

            return RedirectToAction("Add");
        }
    }
}

LeitorNfe2/Controllers/ProductsController.cs
using LeitorNfe2.Data;
using LeitorNfe2.Models;
using LeitorNfe2.Models.Domain;
using Microsoft.AspNetCore.Mvc;
using System.Xml;

namespace LeitorNfe2.Controllers
{
    public class ProductsController : Controller
    {
        private readonly LeitorContext leitorContext;
        public ProductsController(LeitorContext leitorContext)
        {
            this.leitorContext = leitorContext;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddProductViewModel request)
        {
            var product = new Product()
            {
                Id = Guid.NewGuid(),
                ProductCode = request.ProductCode,
                Name = request.Name,
                Amount = request.Amount,
                UnitaryValue = request.UnitaryValue,
                TotalValue = request.TotalValue,
            };

            await leitorContext.Products.AddAsync(product);
            await leitorContext.SaveChangesAsync();

            return RedirectToAction("Add");
        }
    }
}

LeitorNfe2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeitorNfe2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LeitorNfe2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Invoices" asp-action="Index">LeitorNfe2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoices" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Addresses" asp-action="Add">Endereços</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Add">Produtos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Issuers" asp-action="Add">Emitente</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Addressees" asp-action="Add">Destinatário</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoices" asp-action="Add">Nota Fiscal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LeitorNfe2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>